### ISSUE TITLE
Server not reachable: unable to connect to server

### ISSUE THREAD

**Issue by jonathankenbrown** [bitnami/bitnami-docker-parse-dashboard#27]
**Description**

Parse Dashboard Error: 
Server not reachable: unable to connect to server

**Steps to reproduce the issue:**

Using basic commands for docker compose from TL;DR in instruction.

docker-compose.yml:

```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested locally and also "Play with Docker" sandbox.

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by silviofdez** [comment]
Hi,

Could you please provide us a little more information in order to reproduce the issue. Currently, we try to access the web server via web browser after the installation and it works as usual. Which commands are you executing or which ip:port are you trying to access?

**Comment by jonathankenbrown** [comment]
To reproduce what I am seeing:

1. Go to https://labs.play-with-docker.com and spin up an instance.
2. Type in: curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-parse-dashboard/master/docker-compose.yml > docker-compose.yml
3. docker-compose up -d
4. Open port 80 in the browser.

I have tried on the local machine as well. All I am trying to do is follow the TL;DR instruction.

**Comment by javsalgar** [comment]
Hi,

I tried two things. 

  - Locally: The issue did not occur, as you can see in the picture

<img width="937" alt="screen shot 2018-01-03 at 11 23 41" src="https://user-images.githubusercontent.com/1133777/34516790-9623c56a-f078-11e7-81b5-560bf3cdf00a.png">

  - Using Play with Docker: Then the issue happened, as it can be seen here:

<img width="1258" alt="screen shot 2018-01-03 at 11 22 32" src="https://user-images.githubusercontent.com/1133777/34516810-ae0d41ba-f078-11e7-9170-b0ea01554b71.png">

The reason is clear. Parse Dashboard is generating links that reference its IP address (i.e. 172.17...). In the local case, this works without issues as the IP is accessible from my browser. However, in the second case, as it is using the proxy http://ip172-18-0-11-b96as20l9m7g008g08q0-80.direct.labs.play-with-docker.com/, the container IP address is not accessible. Therefore it fails (check the errors in the Chrome console). 

We would need to check if something can be done about it.

**Comment by javsalgar** [comment]
Hi,

Have you tried using the `PARSE_HOST` environment variable? If you set it to 192.168.99.100 it may work. You may need to add the port as well.

**Comment by jonathankenbrown** [comment]
@javsalgar 
Yes, I have tried this and still having the same issue.

**Comment by javsalgar** [comment]
Hi, this is strange. Even after setting PARSE_HOST to 192.168.99.100 you get an error like the one I showed in my screenshot? Could you show me the error in the Chrome console? isn't 192.168.99.100:1337 available for access?

**Comment by dbarranco** [comment]
I would also use `docker inspect` to see which network address space is using the container, just in case it is different

**Comment by jonathankenbrown** [comment]
I have tried PARSE_HOST environment variable pointing to both the default local docker IP 192.168.99.100 and 0.0.0.0. 
I looked at `docker inspect` and the network is assigning 172.19.0.1 (gateway).
Please note, I am new to Docker (but have used bitnami Parse previously).

It appears the issue is with Parse not able to connect to IP associated with MongoDB container.

I would really like to see the bitnami parse-dashboard package to work without requiring much manual config.

**Comment by javsalgar** [comment]
You say it cannot connect to the MongoDB container. Do you see a message in the application mentioning that? We would like to see if there are two different issues or we are talking about the same exact one.

**Comment by lmwu** [comment]
@javsalgar 
Is this question resloved already?
After activating the 3 layers of containers (Parse Dashboard - Parse server - MongoDB) in the AliCloud, I tried to directly login it with web browser overseas. As a result, it failed.

e.g.
http://ip_from_provider:4040/
After login finished, it said,  server not reachable.... 

I also tried to login parse-dashboard in the local platform with RDP, and it works. But I cannot always get RDP to use, especially in different countries which network infra is poor.
How can I successfully get dashboard to use from the external ip?

Thanks.

**Comment by lmwu** [comment]
Hi javsalgar,
Many thanks to you.
I can successfully make RESTful externally. e.g. With the example of curl command to access the parse server.
How should I correct set the PARSE_HOST and  PARSE_PORT_NUMBER environment variables?
I ever gave the   PARSE_HOST=server_ip  in the docker compose file, but it doesn't work.
Would you please provide me the steps. 
Thank you.

**Comment by lmwu** [comment]
@javsalgar 
I just made it by running it manually instead of docker-compose.yml
.... So it cannot be achieve by docker-compose?

**Comment by javsalgar** [comment]
Hi

Could you show the manual commands that made it work and the docker-compose file that does not work?

**Comment by lmwu** [comment]
Hi 
Thanks for concern.

**Work:**
```
# docker run -d --name mongodb --net=parse_dashboard-tier bitnami/mongodb
# docker run -d -p 1337:1337 --name parse --net=parse_dashboard-tier bitnami/parse
# docker run -d -e PARSE_HOST=47.xxx.239.65 -p 4040:4040 --name parse-dashboard --net=parse_dashboard-tier bitnami/parse-dashboard
```
**Not Work (docker-compose.yml):**
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    environment:
      - PARSE_HOST=47.xxx.239.65
    labels:
      kompose.service.type: nodeport
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
Do me a favor to check what the error was from, please.

**Comment by lmwu** [comment]
@javsalgar 

With the docker-compose.yml
![1531218681512](https://user-images.githubusercontent.com/12655592/42504846-945fa5e2-846f-11e8-98a3-651cb366220d.jpg)
As seen in this screenshot, the console had several times of **POST**
```POST http://172.19.0.3:1337/parse/serverInfo 0 ()```
It's strange, I don't have the 172.19.0.* , does the error occurs from the script in docker-compose.yml ?

**Comment by javsalgar** [comment]
Hi,

This is strange. The only difference I see is that of the network (but compose should create one). Could you try setting   `parse-dashboard-tier` as the network? Just in case? https://docs.docker.com/compose/networking/#specify-custom-networks

**Comment by lmwu** [comment]
@javsalgar 
Do I have to install a network driver plugin in advance?
When I tried the "Join a pre-existing network", it still failed.

**Comment by lmwu** [comment]
@javsalgar 
Juz tried what you suggested.
It always fail.
Anyway thank you so much.

**Comment by javsalgar** [comment]
Hi,

This is very strange. If it works using docker, it should work using docker-compose. I will try to set a similar environment and see if I get the same issue.

**Comment by javsalgar** [comment]
Hi,

I used the same exact docker-compose that you used in a clean instance, and did not get any problems accessing. The only command I used is `docker-compose up`.

![image](https://user-images.githubusercontent.com/1133777/42694682-820a0f4a-86b3-11e8-9549-4aa795208b31.png)


This is the docker-compose file that I used.

```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    environment:
      - PARSE_HOST=35.204.211.50
    labels:
      kompose.service.type: nodeport
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

Could you try checking that the issue appears when there is no persistence (`docker-compose down -v`)?
