### ISSUE TITLE
Parse DashBoard Can not Open!

### ISSUE THREAD

**Issue by zhushengwen** [bitnami/bitnami-docker-parse-dashboard#32]
```
 environment:
    - PARSE_HOST=
```
the variable makes no sense.

browser console error:
http://172.18.0.3:1337/parse/serverInfo net::ERR_CONNECTION_TIMED_OUT

**Comment by tompizmor** [comment]
@amarCosmospace 

Can you tell me a bit more about your environment? Are you using Docker for Windows, Docker for Mac, native Docker on Linux,...?

**Comment by amarCosmospace** [comment]
Using docker on mac os (10.14 (18A391)) (Docker version 18.03.1-ce, build 9ee9f40) 
docker-compose version 1.21.1, build 5a3f1a3

**Comment by tompizmor** [comment]
Can you try setting `PARSE_HOST=127.0.0.1`? I just tried on Docker for Mac and worked fine.

**Comment by amarCosmospace** [comment]
Got the exact same issue

```
➜  parse docker-compose ps     
         Name                        Command               State           Ports         
-----------------------------------------------------------------------------------------
parse_mongodb_1           /app-entrypoint.sh /run.sh       Up      27017/tcp             
parse_parse-dashboard_1   /app-entrypoint.sh nami st ...   Up      0.0.0.0:80->4040/tcp  
parse_parse_1             /app-entrypoint.sh nami st ...   Up      0.0.0.0:1337->1337/tcp
➜  parse cat docker-compose.yml 
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    environment:
      - PARSE_HOST=127.0.0.1
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:1'
    environment:
      - PARSE_HOST=127.0.0.1
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
