### ISSUE TITLE
Dashboard tries to connect to wrong IP Endpoint even when PARSE_HOST is set

### ISSUE THREAD

**Issue by broken-bytes** [bitnami/bitnami-docker-parse-dashboard#34]
**Description**

Dashboard tries to connect to wrong IP Endpoint even when PARSE_HOST is set, therefore dashboard is useless in docker compose image.

**Steps to reproduce the issue:**

1. Download yml file from this git repository
2. `run docker-compose up -d`
3. Open Dashboard in browser
4. See console log
5.  http://172.23.0.3:1337/parse/classes/_Installation net::ERR_CONNECTION_TIMED_OUT gets logged even though PARSE_HOST was set to 127.0.0.1

**Describe the results you received:**
Dashboard doesn't connect to parse server instance.

**Describe the results you expected:**

Connection should work 
**Additional information you deem important (e.g. issue happens only occasionally):**
Tested with latest version of docker, docker compose and a fresh `docker-compose pull`
-OS: Debian 9
-Webserver: NGINX

**docker-compose.yml**
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
    ports:
      - '27018:27018'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    environment:
      - PARSE_HOST=127.0.0.1
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local


```

**Comment by javsalgar** [comment]
Hi,

Does setting PARSE_HOST to a different address such as example.com generate the correct links? We would like to check if it is an issue when setting  127.0.0.1 or it is an issue with any value in PARSE_HOST

**Comment by broken-bytes** [comment]
No, it does not change anything. I found the issue though.
Setting the parameters via the -e tag when running each image on its own works.
So when I append -e PARSE_HOST = xxxx the host does get changed.
Looks like this is an issue with the compose environment variable parsing.

**Comment by juan131** [comment]
That's very weird... I'm unable to reproduce the issue. Could you please ensure you don't have any persisted data from previous deployments in the volume `parse_dashboard_data`?

**Comment by i--storm** [comment]
Having the same issue on clean install

**Comment by juan131** [comment]
Hi @i--storm 

Could you please provide us more information about your environment? 
Could you share the `docker-compose.yaml` you're using? I'd like to reproduce your scenario so I can identify the issue.

**Comment by i--storm** [comment]
Hi, juan131
Here is my docker-compose
`version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    volumes:
      - 'parse_data:/bitnami'
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - mongodb
    environment:
      - PARSE_DASHBOARD_USER=user
      - PARSE_DASHBOARD_PASSWORD=123456
      - PARSE_APP_ID=myappID
      - PARSE_MASTER_KEY=mymasterKey
      
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local`

My environment is Docket Toolbox under Windows 10
`$ docker --version
Docker version 18.03.0-ce, build 0520e24302`

**Comment by juan131** [comment]
Hi @i--storm 

Could you please apply the change below into your `docker-compose.yaml` ("parse-dashboard" service)?

```diff
    depends_on:
-      - mongodb
+      - parse
    environment:
+      - PARSE_HOST=127.0.0.1
```

On the other hand, could you also define the env. variables **PARSE_APP_ID** and **PARSE_MASTER_KEY** in the "parse" container (for consistency)?

Please let us know if the changes help you to solve the issue?

**Comment by i--storm** [comment]
I can not use 127.0.0.1 because Docker under Windows runs under virtual machine and it has different IP than host.

**Comment by juan131** [comment]
Hi @i--storm 

Could you use the IP assigned to your Docker VM instead?

**Comment by i--storm** [comment]
I've entered 192.168.99.100. It is IP address of virtual machine. I can access Parse Dashboard page on this address, but when I enter login/password it hangs and in console it's trying to access 172.20.0.3
https://yadi.sk/i/XWbxGA9Z4L95zQ

**Comment by juan131** [comment]
Could you add the env. variable below to your docker-compose.yml (parse-dashboard section)?

```yaml
    environment:
      - NAMI_DEBUG='--log-level=trace'
```

Then start from scratch your deployment share with us what you obtain when executing the command below:

```bash
$ docker-compose logs parse-dashboard
```

**Comment by i--storm** [comment]
```
$ docker-compose logs parse-dashboard
Attaching to bitnamiparsedashboard_parse-dashboard_1
parse-dashboard_1  | app-entrypoint.sh 09:55:06.36
parse-dashboard_1  | app-entrypoint.sh 09:55:06.37 Welcome to the Bitnami parse-dashboard container
parse-dashboard_1  | app-entrypoint.sh 09:55:06.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-parse-dashboard
parse-dashboard_1  | app-entrypoint.sh 09:55:06.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-parse-dashboard/issues
parse-dashboard_1  | app-entrypoint.sh 09:55:06.38
parse-dashboard_1  | nami    INFO  Initializing parse-dashboard
parse-dashboard_1  | parse-d DEBUG Creating Parse Dashboard system user...
parse-dashboard_1  | parse-d TRACE [restorePersistedData] Restoring /bitnami/parse-dashboard/config.json to /opt/bitnami/parse-dashboard/config.json
parse-dashboard_1  | parse-d INFO
parse-dashboard_1  | parse-d INFO  ########################################################################
parse-dashboard_1  | parse-d INFO   Installation parameters for parse-dashboard:
parse-dashboard_1  | parse-d INFO     Persisted data and properties have been restored.
parse-dashboard_1  | parse-d INFO     Any input specified will not take effect.
parse-dashboard_1  | parse-d INFO   This installation requires no credentials.
parse-dashboard_1  | parse-d INFO  ########################################################################
parse-dashboard_1  | parse-d INFO
parse-dashboard_1  | nami    INFO  parse-dashboard successfully initialized
parse-dashboard_1  | app-entrypoint.sh 09:55:13.19 INFO  ==> Starting parse-dashboard...
parse-dashboard_1  | The dashboard is now available at http://0.0.0.0:4040/
parse-dashboard_1  | app-entrypoint.sh 09:56:30.48
parse-dashboard_1  | app-entrypoint.sh 09:56:30.48 Welcome to the Bitnami parse-dashboard container
parse-dashboard_1  | app-entrypoint.sh 09:56:30.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-parse-dashboard
parse-dashboard_1  | app-entrypoint.sh 09:56:30.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-parse-dashboard/issues
parse-dashboard_1  | app-entrypoint.sh 09:56:30.50
parse-dashboard_1  | app-entrypoint.sh 09:56:33.87 INFO  ==> Starting parse-dashboard...
parse-dashboard_1  | The dashboard is now available at http://0.0.0.0:4040/
```

**Comment by tompizmor** [comment]
Hi @i--storm,

I think you are missing one environment variable in your docker-compose file. You need to specify to parse-dashboard where is the Parse server. For that, you need to specify the PARSE_HOST env var to the parse-dashboard container.

Can you try with this docker-compose file?

```
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    volumes:
      - 'parse_data:/bitnami'
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - mongodb
    environment:
      - PARSE_DASHBOARD_USER=user
      - PARSE_HOST=192.168.99.100
      - PARSE_DASHBOARD_PASSWORD=123456
      - PARSE_APP_ID=myappID
      - PARSE_MASTER_KEY=mymasterKey
      
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

**Comment by i--storm** [comment]
Hi, @tompizmor, my full docker-compose.yml now
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    volumes:
      - 'parse_data:/bitnami'
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '8085:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:      
      - NAMI_DEBUG='--log-level=trace'
      - PARSE_HOST=192.168.99.100
      - PARSE_DASHBOARD_USER=user
      - PARSE_DASHBOARD_PASSWORD=1q2we3r4
      - PARSE_APP_ID=myappID
      - PARSE_MASTER_KEY=mymasterKey
      
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
Problem is that Dash board do not receive this variable.

**Comment by juan131** [comment]
Hi @broken-bytes 

Did you remove your volumes? You might be starting Parse Dashboard with configuration from previous deployments... Try running the commands below to avoid that:

```bash
$ docker-compose down -v 
$ docker-compose up -d
```

**Comment by tompizmor** [comment]
You can also exec into the parse-dashboard container and execute this command to see the URL configured.

```
cat /opt/bitnami/parse-dashboard/config.json | grep serverURL
```

If it is receiving the variable you should see `      "serverURL": "http://192.168.99.100:1337/parse",`

**Comment by broken-bytes** [comment]
> Hi @broken-bytes
> 
> Did you remove your volumes? You might be starting Parse Dashboard with configuration from previous deployments... Try running the commands below to avoid that:
> 
> ```shell
> $ docker-compose down -v 
> $ docker-compose up -d
> ```

No, this was the initial installment

**Comment by juan131** [comment]
Hi @broken-bytes 

Did you check the configuration file (**/opt/bitnami/parse-dashboard/config.json**) as suggested by @tompizmor ?

**Comment by remoblaser** [comment]
Well, just stumbled upon this as well. You're actually hardcoding http in `/opt/bitnami/parse-dashboard/config.json`. Thus it's impossible to use HTTPS. I'm running parse via helm chart in a k8s cluster and would need to manually replace this config everytime a pod starts or create a volume just for the config.

**Comment by javsalgar** [comment]
Hi,

Are you using ingress in K8s? The ingress controller should be the one with HTTPS and then forward to HTTP.

**Comment by remoblaser** [comment]
That won't solve the problem though as the dashboard is still generating HTTP links or am I wrong`?

**Comment by dani8art** [comment]
Hi @remoblaser,

You are right, we are hardcoding HTTP and sometimes HTTPS is required. I will proceed to create an internal task to evaluate supporting HTTPS configuration.

Thanks so much for your feedback. We'll keep you updated about our advances.

Regards.

**Comment by dani8art** [comment]
Hi @remoblaser 

We have just fixed this issue in parse helm chart so you can use HTTPS for your k8s deployments just using `dashboard.parseServerUrlProtocol`. It should be set to `https` then parse-dashboard will use it to form the URLs. 

It can be directly set on the helm command adding:
```shell
## helm 2
#
helm install --name my-parse --set dashboard.parseServerUrlProtocol=https stable/parse 

## helm 3
#
helm install my-parse --set dashboard.parseServerUrlProtocol=https stable/parse 
``` 
or set it in your `values.yaml`:
```yaml
dashboard:
  ...
  parseServerUrlProtocol: "https" 
  ...
```
