### ISSUE TITLE
 strict-origin-when-cross-origin error when parse dashboard makes serverinfo and schema request

### ISSUE THREAD

**Issue by jsgit3276** [bitnami/bitnami-docker-parse-dashboard#50]
### Name and Version

docker.io/bitnami/parse-dashboard:3

### What steps will reproduce the bug?

Installed parse on my local machine using docker compose. When i log into Parse dashboard it loads blank page. When i inspect i see all calls fail with "Referrer Policy:strict-origin-when-cross-origin"

```
version: '2'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=admin
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=admin
  parse:
    image: docker.io/bitnami/parse:4
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami/parse'
    depends_on:
      - mongodb
    environment:
      - PARSE_HOST=192.168.1.181
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=admin
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=admin
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:3
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      - PARSE_HOST=192.168.1.181

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

### What do you see instead?

Request URL: http://192.168.1.181:1337/parse/serverInfo
Referrer Policy: strict-origin-when-cross-origin
