### ISSUE TITLE
can't start the server when open cloud code

### ISSUE THREAD

**Issue by zero16832** [bitnami/bitnami-docker-parse-dashboard#51]
### Name and Version

parse-server:last

### What steps will reproduce the bug?
```
version: '2'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:latest
    volumes:
      - './mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PARSE_DATABASE_HOST=127.0.0.1
      - MONGODB_USERNAME=bn_parse
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=bitnami123
  parse:
    image: docker.io/bitnami/parse:latest
    ports:
      - '1337:1337'
    volumes:
      - './parse_data:/bitnami'
      - './cloud:/opt/bitnami/parse/cloud'
    depends_on:
      - mongodb
    environment:
      - PARSE_ENABLE_CLOUD_CODE=yes
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=bn_parse
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=bitnami123
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:latest
    ports:
      - '80:4040'
    volumes:
      - './parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      - PARSE_DASHBOARD_PARSE_HOST=127.0.0.1
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

### What is the expected behavior?

no

### What do you see instead?

no

### Additional information

when i set  - PARSE_ENABLE_CLOUD_CODE=no ,the parse-server can't run,it call:
```
internal/modules/cjs/loader.js:905

  throw err;

  ^


Error: Cannot find module '/cloud/main.js'

Require stack:

- /opt/bitnami/parse/lib/ParseServer.js

- /opt/bitnami/parse/lib/index.js

- /opt/bitnami/parse/lib/cli/parse-server.js

- /opt/bitnami/parse/bin/parse-server

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)

    at Function.Module._load (internal/modules/cjs/loader.js:746:27)

    at Module.require (internal/modules/cjs/loader.js:974:19)

    at require (internal/modules/cjs/helpers.js:101:18)

    at new ParseServer (/opt/bitnami/parse/lib/ParseServer.js:158:9)

    at Function.start (/opt/bitnami/parse/lib/ParseServer.js:364:25)

    at start (/opt/bitnami/parse/lib/cli/parse-server.js:90:22)

    at _default (/opt/bitnami/parse/lib/cli/utils/runner.js:61:3)

    at Object.<anonymous> (/opt/bitnami/parse/lib/cli/parse-server.js:38:21)

    at Module._compile (internal/modules/cjs/loader.js:1085:14) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/opt/bitnami/parse/lib/ParseServer.js',

    '/opt/bitnami/parse/lib/index.js',

    '/opt/bitnami/parse/lib/cli/parse-server.js',

    '/opt/bitnami/parse/bin/parse-server'

  ]

}
```
what the problem with that? thx for your help!
