### ISSUE TITLE
Some Setting Bug

### ISSUE THREAD

**Issue by zero16832** [bitnami/bitnami-docker-parse-dashboard#52]
### Name and Version

last

### What steps will reproduce the bug?
```yaml
version: '2'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=bn_parse
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=bitnami123
  parse:
    image: docker.io/bitnami/parse:latest
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
      - './cloud:/opt/bitnami/parse/cloud'
    depends_on:
      - mongodb
    environment:
      - PARSE_ENABLE_CLOUD_CODE=yes
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=bn_parse
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=bitnami123
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:latest
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      - PARSE_DASHBOARD_PARSE_HOST=127.0.0.1
      - PARSE_DASHBOARD_PARSE_APP_NAME=DEMOProject
      - PARSE_DASHBOARD_PARSE_APP_ID=DEMOProject_AppID
      - PARSE_DASHBOARD_PARSE_MASTER_KEY=DEMOProject_MasterKey
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

### What is the expected behavior?

the setting like that, the parse-dashboard can't run. I just set my project name and appid and masterid. The parse-dashboard server can't run.
