### ISSUE TITLE
Server not reachable: unable to connect to server

### ISSUE THREAD

**Issue by maaazaaam** [bitnami/bitnami-docker-parse-dashboard#9]
Hello,

I tried this ready-made system on my macbook with this docker-compose.yml : 
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - '/Users/me/docker/parse-server/data/mongodb_data:/bitnami/mongodb'
  parse:
    image: 'bitnami/parse:latest'
    environment:
     - PARSE_SERVER_HOST=localhost
    volumes:
      - '/Users/me/docker/parse-server/data/parse_data:/bitnami/parse'
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
  application:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    volumes:
      - '/Users/me/docker/parse-server/data/parse_dashboard_data:/bitnami/parse-dashboard'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

all start good, but when I connect to the dashboard with Chrome on http://localhost I have an error  

> Server not reachable: unable to connect to server

Someone knows what I did bad ?

Thanks for your help !
Maz.

**Comment by sameersbn** [comment]
Hello, You should move `PARSE_SERVER_HOST=localhost` to the parse-dashboard containers environment like so:

```yaml
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - '/Users/me/docker/parse-server/data/mongodb_data:/bitnami/mongodb'
  parse:
    image: 'bitnami/parse:latest'
    volumes:
      - '/Users/me/docker/parse-server/data/parse_data:/bitnami/parse'
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
  application:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    volumes:
      - '/Users/me/docker/parse-server/data/parse_dashboard_data:/bitnami/parse-dashboard'
    depends_on:
      - mongodb
    environment:
     - PARSE_SERVER_HOST=localhost
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
